<!-- Generated by Trae Work -->
<template>
  <div class="modal-overlay" @click.self="state.nextLevel()">
    <div class="modal shop-modal">
      <h2>🛒 小丑商店</h2>
      <div class="shop-info">💰 {{ game.money }} 金币 | 小丑位 {{ game.jokers.length }}/6</div>

      <div class="shop-layout">
        <div class="shop-left">
          <!-- 小丑牌 -->
          <div class="shop-section">
            <div class="section-label">🃏 小丑牌</div>
            <div class="shop-grid">
              <div v-for="(item, idx) in state.shopItems.value" :key="idx" class="shop-item">
                <JokerCard
                  :def="item.def"
                  :sold="item.sold"
                  size="sm"
                  @hover="(e, def) => showJokerTip(e, def, item.def.cost)"
                  @leave="hideTip"
                />
                <div class="si-price">${{ item.def.cost }}</div>
                <button
                  class="buy-btn"
                  :disabled="item.sold || game.money < item.def.cost || game.jokers.length >= 6"
                  @click="state.buyShopItem(idx)"
                >{{ item.sold ? '已售' : '购买' }}</button>
              </div>
            </div>
          </div>

          <!-- 消耗品 -->
          <div class="shop-section">
            <div class="section-label">🔮 消耗品</div>
            <div class="shop-grid">
              <div v-for="(item, idx) in state.shopConsumables.value" :key="idx" class="shop-item">
                <ConsumableCard
                  :def="item.def"
                  :type="item.type"
                  :sold="item.sold"
                  size="sm"
                  @hover="(e, def) => showConsTip(e, def, item.type, item.def.cost)"
                  @leave="hideTip"
                />
                <div class="si-price">${{ item.def.cost }}</div>
                <button
                  class="buy-btn"
                  :disabled="item.sold || game.money < item.def.cost || game.consumables.length >= 2"
                  @click="state.buyConsumable(idx)"
                >{{ item.sold ? '已售' : '购买' }}</button>
              </div>
            </div>
          </div>

          <div class="shop-actions">
            <button class="btn btn-sort" @click="state.rerollShop()">🔄 刷新 (${{ rerollCost }})</button>
            <button class="btn btn-play" @click="state.nextLevel()">▶ 下一层</button>
          </div>
        </div>

        <!-- 右侧：持有 -->
        <div class="shop-right">
          <div class="owned-section">
            <div class="owned-label">当前小丑牌 (点击卖出)</div>
            <div class="owned-grid">
              <div v-for="(joker, idx) in game.jokers" :key="idx" class="owned-card-wrap">
                <JokerCard
                  :def="getJokerDef(joker)"
                  size="sm"
                  :locked="joker.data?.locked"
                  :confirm-mode="confirming === `joker-${idx}`"
                  @hover="(e, def) => showOwnedJokerTip(e, def, joker)"
                  @leave="hideTip"
                  @click="handleSellJoker(idx)"
                />
              </div>
              <div v-if="game.jokers.length === 0" class="empty-text">暂无</div>
            </div>
          </div>
          <div class="owned-section">
            <div class="owned-label">当前消耗品 (点击卖出)</div>
            <div class="owned-grid">
              <div v-for="(cons, idx) in game.consumables" :key="idx" class="owned-card-wrap">
                <ConsumableCard
                  :def="getConsDef(cons)"
                  :type="cons.type"
                  size="sm"
                  :confirm-mode="confirming === `cons-${idx}`"
                  @hover="(e, def) => showOwnedConsTip(e, def, cons.type)"
                  @leave="hideTip"
                  @click="handleSellCons(idx)"
                />
              </div>
              <div v-if="game.consumables.length === 0" class="empty-text">暂无</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- 全局 Tooltip -->
  <Tooltip
    :visible="tip.visible"
    :x="tip.x"
    :y="tip.y"
    :icon="tip.icon"
    :name="tip.name"
    :subtitle="tip.subtitle"
    :desc="tip.desc"
    :extra="tip.extra"
  />
</template>

<script setup>
import { ref, reactive, computed } from 'vue'
import { getJoker } from '../utils/gameData.js'
import { getConsumableDef } from '../utils/gameData.js'
import { RARITY_NAMES } from '../data/constants.js'
import JokerCard from './game/JokerCard.vue'
import ConsumableCard from './game/ConsumableCard.vue'
import Tooltip from './common/Tooltip.vue'

const props = defineProps({ state: Object })
const game = props.state.game

const confirming = ref(null) // 'joker-N' | 'cons-N' | null

const rerollCost = computed(() => 1 + game.rerollCount)

// ---------- Tooltip ----------
const tip = reactive({
  visible: false, x: 0, y: 0,
  icon: '', name: '', subtitle: '', desc: '', extra: '',
})

function showJokerTip(e, def, cost) {
  Object.assign(tip, {
    visible: true,
    x: e.clientX + 12, y: e.clientY,
    icon: def.icon, name: def.name,
    subtitle: `${RARITY_NAMES[def.rarity]} · $${cost}`,
    desc: def.desc,
    extra: '',
  })
}

function showConsTip(e, def, type, cost) {
  Object.assign(tip, {
    visible: true,
    x: e.clientX + 12, y: e.clientY,
    icon: def.icon, name: def.name,
    subtitle: `${type === 'tarot' ? '塔罗牌' : '星球牌'} · $${cost}`,
    desc: def.desc,
    extra: '',
  })
}

function showOwnedJokerTip(e, def, joker) {
  const sellPrice = Math.max(1, Math.floor(def.cost / 2))
  const locked = joker.data?.locked
  Object.assign(tip, {
    visible: true,
    x: e.clientX + 12, y: e.clientY,
    icon: def.icon, name: def.name,
    subtitle: `${RARITY_NAMES[def.rarity]} · 卖出价 $${sellPrice}`,
    desc: def.desc,
    extra: locked ? '🔒 锁定，不可卖出' : '',
  })
}

function showOwnedConsTip(e, def, type) {
  Object.assign(tip, {
    visible: true,
    x: e.clientX + 12, y: e.clientY,
    icon: def.icon, name: def.name,
    subtitle: type === 'tarot' ? '塔罗牌' : '星球牌',
    desc: def.desc,
    extra: '',
  })
}

function hideTip() { tip.visible = false }

// ---------- 卖出 ----------

function handleSellJoker(idx) {
  const joker = game.jokers[idx]
  if (joker?.data?.locked) {
    props.state.showToast('锁定的小丑不能卖出!')
    return
  }
  if (confirming.value === `joker-${idx}`) {
    props.state.sellJoker(idx)
    confirming.value = null
  } else {
    confirming.value = `joker-${idx}`
  }
}

function handleSellCons(idx) {
  if (confirming.value === `cons-${idx}`) {
    props.state.sellConsumable(idx)
    confirming.value = null
  } else {
    confirming.value = `cons-${idx}`
  }
}

// ---------- 辅助 ----------
function getJokerDef(joker) { return getJoker(joker.id) || {} }
function getConsDef(cons) { return getConsumableDef(cons.type, cons.id) || {} }
</script>

<style scoped>
.modal-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.7); backdrop-filter: blur(6px); display: flex; align-items: center; justify-content: center; z-index: 200; }
.modal { background: linear-gradient(145deg, rgba(20,15,40,0.98), rgba(15,10,30,0.98)); border: 1px solid rgba(255,204,34,0.3); border-radius: 16px; padding: 20px; max-width: 720px; width: 92%; max-height: 90vh; overflow-y: auto; box-shadow: 0 0 40px rgba(255,204,34,0.15); }
h2 { font-size: 20px; color: var(--gold); margin-bottom: 8px; text-align: center; }
.shop-info { text-align: center; font-size: 12px; color: var(--muted); margin-bottom: 12px; }
.shop-layout { display: flex; gap: 16px; }
.shop-left { flex: 1; }
.shop-right { width: 170px; flex-shrink: 0; }
.shop-section { margin-bottom: 12px; }
.section-label { font-size: 13px; font-weight: 700; color: var(--accent2); margin-bottom: 8px; }
.shop-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(90px, 1fr)); gap: 10px; }
.shop-item { text-align: center; display: flex; flex-direction: column; align-items: center; gap: 4px; }
.si-price { font-size: 13px; color: var(--gold); font-weight: 700; }
.buy-btn {
  background: linear-gradient(135deg, var(--green), #00aa5e); color: #fff; border: none;
  border-radius: 6px; padding: 4px 14px; font-size: 11px; font-weight: 700; cursor: pointer;
}
.buy-btn:disabled { opacity: 0.4; cursor: not-allowed; background: var(--muted); }
.shop-actions { display: flex; gap: 8px; justify-content: center; margin-top: 8px; }
.owned-section { margin-bottom: 12px; }
.owned-label { font-size: 11px; color: var(--muted); margin-bottom: 6px; }
.owned-grid { display: flex; flex-wrap: wrap; gap: 6px; }
.owned-card-wrap { position: relative; }
.empty-text { color: var(--muted); font-size: 10px; padding: 8px; }
</style>
